### ISSUE TITLE
fixed footer

### ISSUE THREAD

**Issue by jcolscript** [diegochagas/saint-seiya-api#4]
https://github.com/diegochagas/saint-seiya-api/blob/1deda61f2108b6e4a88686686515110bcf8f5bf8/frontend/src/app/shared/components/footer/footer.component.scss#L1-L9

`.footer {
    position: absolute;
    z-index: 3;
    color: white;
    background-color: black;
    display: flex;
    flex-wrap: wrap;
    justify-content: space-around;
    min-height: 218px;
    width: 100%;
}`

**Comment by diegochagas** [comment]
Thanks for the tip @jcolscript , I fixed the min-height of the footer.
