### ISSUE TITLE
background 100% in body

### ISSUE THREAD

**Issue by jcolscript** [diegochagas/saint-seiya-api#5]
https://github.com/diegochagas/saint-seiya-api/blob/1deda61f2108b6e4a88686686515110bcf8f5bf8/frontend/src/styles.scss#L1-L4

`body {
  position: relative;
  margin: 0;
  font-family: Roboto, "Helvetica Neue", sans-serif;
  min-height: 100vh;
}`

**Comment by diegochagas** [comment]
Thanks for the tip @jcolscript . I fixed the min-height of the body.
